server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    location / {
        return 200 "HTTPS Working!";
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    return 301 https://$host$request_uri;
}
