BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  tier text NOT NULL DEFAULT 'bronze' CHECK (tier IN ('bronze', 'silver', 'gold')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  price numeric(10, 2) NOT NULL CHECK (price > 0),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_reference text NOT NULL UNIQUE,
  customer_id uuid NOT NULL REFERENCES app.customers(id),
  status text NOT NULL CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled')),
  total_amount numeric(10, 2) NOT NULL DEFAULT 0,
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.order_items (
  order_id bigint NOT NULL REFERENCES app.orders(id) ON DELETE CASCADE,
  line_no smallint NOT NULL,
  product_id bigint NOT NULL REFERENCES app.products(id),
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(10, 2) NOT NULL CHECK (unit_price > 0),
  PRIMARY KEY (order_id, line_no)
);

CREATE TABLE IF NOT EXISTS app.inventory_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES app.products(id),
  movement_type text NOT NULL CHECK (movement_type IN ('in', 'out', 'reserved', 'released')),
  quantity integer NOT NULL CHECK (quantity > 0),
  source_reference text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (product_id, movement_type, source_reference)
);

CREATE TABLE IF NOT EXISTS app.outbox_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_type text NOT NULL,
  aggregate_id text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);

GRANT USAGE ON SCHEMA app TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT USAGE, SELECT ON SEQUENCES TO app;

COMMIT;